### ISSUE TITLE
TODO List for release

### ISSUE THREAD

**Issue by cp2004** [cp2004/OctoPrint-WLED#2]
This plugin works, but these are the things I want to add to it
* [x] Lights on or off button
* [x] Progress effect - use WLED 'percent' effect, change speed/intensity to control.
* [x] Printing event/effect  #3 
* [ ] Discovery of WLED devices - not release blocker - use the discovery plugin that is already there.
* [ ] Investigate realtime control? https://github.com/cp2004/OctoPrint-WS281x_LED_Status/pull/104 - not release blocker

**Comment by FHOGPHIL** [comment]
Bed.nozzle warm up progress would be cool. Was great to switch from RPi control to WLED.
